hawkular/hawkular-alerts

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/Alert.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/AvailabilityCondition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/AvailabilityConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/CompareCondition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/CompareConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/Condition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/StringCondition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/StringConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ThresholdCondition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ThresholdConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ThresholdRangeCondition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ThresholdRangeConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/data/Availability.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/data/Data.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/data/NumericData.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/data/StringData.java, hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/messages/AlertData.java, hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/engine/rules/ConditionMatch.drl, hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/RulesEngineTest.java
May also help with potential temporal reasoning, correlation, and more robust notification. The
timestamps are supplied by the app sending the Data and will default to
system time.
Also:
- Change XxxConditionEval constructors to pass in the relevant Data objects.
A little cleaner in the rules, and a bit more flexible.
- update and standardize the model's toString() impls given the new fields
and variations in the previous impls. Used Eclipse's generator.
- update equals/hashcode impls due to field additions. Used Eclipse generators.
=> Add Data timestamps to allow time-ordered insertions.

hawkular-alerts-api/pom.xml, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/action/Action.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/Alert.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/AvailabilityCondition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/AvailabilityConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/CompareCondition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/CompareConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/Condition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/StringCondition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/StringConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ThresholdCondition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ThresholdConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ThresholdRangeCondition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ThresholdRangeConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/dampening/Dampening.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/data/Availability.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/data/Data.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/data/NumericData.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/data/StringData.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/trigger/Trigger.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/trigger/TriggerTemplate.java, hawkular-alerts-api/src/test/java/org/hawkular/alerts/api/JsonTest.java, hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/engine/rules/ConditionMatch.drl, hawkular-alerts-rest/src/test/groovy/org/hawkular/alerts/rest/AvailabilityConditionsTest.groovy, hawkular-alerts-rest/src/test/groovy/org/hawkular/alerts/rest/CompareConditionsTest.groovy
As a previous step to review REST end points, I have added Json annotations into the API model.
This can also help in the documentation between interaction from Java vs JSON model.
So, with this approach we can avoid to maintain a parallel model inside the engine.
REST endpoints are not yet reviewed, those will come in future commits.
=> Add Json anotations into API model

README.adoc
Just a small change to `README.adoc` to display the build status in travis.
=> Adding Travis-ci badge to project readme

hawkular-alerts-engine/pom.xml, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/DroolsRulesEngineImpl.java, hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/engine/rules/ConditionMatch.drl, hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/PerfRulesEngineTest.java, hawkular-alerts-engine/src/test/resources/log4j.xml
I have created a new profile (-Pperf) which will run specific performance tests for the rules engine.
These tests are a start point to get measures of how respond our model in high congestion of definitions and data.
The idea is to have some preliminar work in this area, these ones are not "integration" tests that should focus wide end-to-end scenarios, these ones are extensions of unit tests but focus in the rule engine.
This can help us in the future to identify regressions and points to improve.
=> HWKALERTS-29 Performance tests

hawkular-actions-api/src/main/java/org/hawkular/actions/api/log/MsgLogger.java, hawkular-actions-sms/pom.xml, hawkular-actions-sms/src/main/java/org/hawkular/actions/sms/listener/SmsListener.java, hawkular-actions-sms/src/test/java/org/hawkular/actions/sms/listener/SmsListenerTest.java, hawkular-alerts-engine/src/main/resources/hawkular-alerts/actions.data, hawkular-alerts-engine/src/test/resources/hawkular-alerts/actions.data, pom.xml
The plugin expects to find a few system properties to configure the Twilio client:
service id, token, from number
If the client can't be initialized, an error message is logged and when messages arrive they're just dropped.
The PR has a unit test and the integration was tested with a free Twilio account
=> HWKALERTS-31 Create a Twilio SMS notification sender

hawkular-alerts-rest/pom.xml
To enable generation of docs when offline. Currently there is a ling to github, this won't work without connection to internet. I've moved the template file into build tools repo. Parent module depends on it, and everything depends on parent module, so it should be cached in local mvn repo for all hawkular modules.
=> Moving the mustache template (for the rest docs) to build tools 

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/StandaloneAlerts.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java, hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/CassTest.java
Small commit to add a helper factory for standalone cases.
It is mainly used for tests/demo purposes but I think it is more clear rather than invoking directly the implementations.
I have thought to do it in a pure SPI style but inter-dependencies have to be resolved manually in anycase so I decided to bring a small factory for it.
=> HWKALERTS-44 Add a standalone factory

.travis.swagger.sh
Check on the consumer side is made also here https://github.com/hawkular/hawkular.github.io/blob/pages/.travis.swagger.sh#L23
=> don't push empty REST documentation

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/AlertsService.java, hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/listener/AlertDataListener.java, hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/listener/AvailDataListener.java, hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/listener/MetricDataListener.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/StandaloneAlerts.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassCluster.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassStatement.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/DbAlertsServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/DbDefinitionsServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/service/AlertsEngine.java, hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/DbDefinitionsTest.java, hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/DefinitionsTest.java, hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/AlertsHandler.java
Refactor such that AlertsService and Impl does not handle both client requests and engine running concerns.  Allow client requests (like getAlerts) to be serviced by a pool of beans, while maintaining the singleton for the engine.
=> Hwkalerts 54

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/Alert.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/AlertsCriteria.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/LifecycleITest.groovy, hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/AlertsHandler.java
Add a "thin" query param to Alerts GET endpoint.  It currently will remove
the evalSets and resolvedEvalSets from the Alerts returned from the fetch.
This can be a good option for an initial list of alerts, where a more
robust pull of alert details can be deferred.
=> HWKALERTS-56 : Need a way to fetch Alerts without the evaluations

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/AvailabilityConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/CompareConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ExternalConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/StringConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ThresholdConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ThresholdRangeConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/data/Availability.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/data/Data.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/data/NumericData.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/data/StringData.java, hawkular-alerts-api/src/test/java/org/hawkular/alerts/api/JsonJacksonTest.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/MemActionsServiceImpl.java, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/LifecycleITest.groovy
Allow any datum sent into Alerting for evaluation to carry optional,
non-matching contextual data.  This data can then be used by Alert
consumers, via the "evalsSet", to better understand the context in
which the data was collected.  For example, for a slow Tx, perhaps the
TxId, or even a query string.
=> HWKALERTS-62 Allow any data to store contextual information

hawkular-alerts-api/pom.xml, hawkular-alerts-engine/pom.xml, hawkular-alerts-rest/pom.xml
This solves the alerts component only.  Change the wordnik (swagger)
dependency scopes to provided. The -Pdocgen stuff is performed at
compile-time only.  We don't need the support at runtime so using
'provided' is the way to limit the transitive imports.  Note that the
engine module was actually depending on the transitive deps via the
api module, so we needed to add fasterxml deps to engine. We do this
via resteasy, which we can set as provided by WFly.  (although, I'm not
sure if we may want to use explicit fasterxml deps in the future to be
more explicit and to potentially protect against actually needed resteasy)
=> HAWKULAR-428 Reduce swagger packaging

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/DefinitionsService.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java, hawkular-alerts-engine/src/main/resources/hawkular-alerts.properties, hawkular-alerts-engine/src/test/resources/hawkular-alerts.properties
With this PR we refresh the cached C* session on Definitions and Alerts services.
Then for slow C* startup it will try to connect in each access avoiding long error logs.
Also number of attempts and timeout was also increased.
=> HAWKULAR-432 Refresh C* session and increase timeout

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/Alert.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/trigger/Trigger.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/trigger/TriggerTemplate.java, hawkular-alerts-api/src/test/java/org/hawkular/alerts/api/JsonJacksonTest.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassStatement.java, hawkular-alerts-engine/src/main/resources/hawkular-alerts-schema.cql, hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/engine/rules/ConditionMatch.drl, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/LifecycleITest.groovy
User can now optionally add a String Map of context data to a Trigger
definition.  The context data will automatically be applied to Alerts
generated for the trigger.
=> HWKALERTS-73 Add context data to Triggers

hawkular-alerts-actions-plugins/hawkular-alerts-actions-file/src/main/java/org/hawkular/alerts/actions/file/FilePlugin.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/Alert.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/dampening/Dampening.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassCluster.java, hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/engine/rules/ConditionMatch.drl, hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/RulesEngineTest.java, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/DampeningITest.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/LifecycleITest.groovy
Change approach to support dampening for ANY-Match triggers.  The change moves the current condition eval set from working memory (as facts in the rule engine) to the trigger's Dampening record itself.  This actually ended up having some addition benefits other than allowing ANY-Match dampening:
- It simplified the rules and removed the condition limit for ALL-Match triggers (was 4 conditions).
- After repeated runs of the -Pperf engine unit tests I see engine execution speed reduced by ~37%!
After rebasing on master this PR branch had some work done to resolve issues unrelated to the dampening issue that can also be reviewed:
- The File action plugin needed to be adapted to work on windows
- The CassCluster.getSession() method was made synchronized.
=> Hwkalerts 74

hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/main/resources/template.html.default_en_US.ftl, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/main/resources/template.plain.default_en_US.ftl, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/resources/template.html.default_en_US.ftl, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/resources/template.plain.default_en_US.ftl, hawkular-alerts-actions-plugins/hawkular-alerts-actions-file/src/test/java/org/hawkular/alerts/actions/file/FilePluginTest.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/CommonData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/JvmGarbageCollectionData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/JvmHeapUsageData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/JvmNonHeapUsageData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/MultipleAllJvmData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/UrlAvailabilityData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/UrlResponseTimeData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/WebActiveSessionsData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/WebContainerCurrentThreadsData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/WebContainerPendingRequestsData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/WebExpiredSessionsData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/WebRejectedSessionsData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/WebRequestsResponseTimeData.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/Alert.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/AlertsService.java, hawkular-alerts-api/src/test/java/org/hawkular/alerts/api/JsonTest.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java, hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/PersistenceTest.java, hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/AlertsHandler.java
Main goals:
- Moved ackNotes and resolvedNotes into generic notes.
- Add additional API service and endpoint to add notes without state transitions.
- Refactor email plugin templates to support generic notes.
@jshaughn please, could you take a look on it ? Thx.
=> HWKALERTS-93 Add generic comments at Alert level

hawkular-alerts-actions-bus/pom.xml, hawkular-alerts-actions-plugins/pom.xml, hawkular-alerts-bus/pom.xml
There are modules that depend on hawkular-bus-mdb but they only use classes in
hawkular-bus-common. This clean up helps with ongoing work for HAWKULAR-732.
=> clean up bus/activemq related deps

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/event/Event.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java
DEBUG on/off was important.
Generated alerts with automatic id can come into collision when testing same trigger.
This is rare but possible.
=> HWKALERTS-98 Fix collision on fast alerts

hawkular-alerts-actions-plugins/hawkular-alerts-actions-aerogear/src/main/webapp/WEB-INF/jboss-web.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-aerogear/src/main/webapp/WEB-INF/web.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/main/webapp/WEB-INF/jboss-web.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/main/webapp/WEB-INF/web.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-file/src/main/webapp/WEB-INF/jboss-web.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-file/src/main/webapp/WEB-INF/web.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/src/main/webapp/WEB-INF/jboss-web.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/src/main/webapp/WEB-INF/web.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-pagerduty/src/main/webapp/WEB-INF/jboss-web.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-pagerduty/src/main/webapp/WEB-INF/web.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-sms/src/main/webapp/WEB-INF/jboss-web.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-sms/src/main/webapp/WEB-INF/web.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-snmp/src/main/webapp/WEB-INF/jboss-web.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-snmp/src/main/webapp/WEB-INF/web.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/java/org/hawkular/alerts/actions/webhook/accounts/PersonaFilter.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/webapp/WEB-INF/web.xml
This PR is trivial to fix missing keycloak config on plugins .war archives.
In theory, plugins don't expose Web, but to not leave open holes it is good to be consistent.
=> HWKALERTS-120 Add missing keycloak config on hawkular deployments

hawkular-alerts-bus-api/src/main/java/org/hawkular/alerts/bus/api/AlertDataMessage.java, hawkular-alerts-bus-api/src/main/java/org/hawkular/alerts/bus/api/AvailDataMessage.java, hawkular-alerts-bus-api/src/main/java/org/hawkular/alerts/bus/api/MetricDataMessage.java, hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/listener/AlertDataListener.java, hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/listener/AvailDataListener.java, hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/listener/MetricDataListener.java
Future messages used by the bus should be placed on the public api for external users.
=> HWKALERTS-119 Move Bus messages to public API

hawkular-alerts-rest-tests/pom.xml, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/AbstractITestBase.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/BusITest.groovy, hawkular-alerts-rest-tests/src/test/resources/application-roles.properties, hawkular-alerts-rest-tests/src/test/resources/application-users.properties, hawkular-alerts-rest-tests/src/test/resources/standalone-hawkular.xsl
Minor PR to cover bus scenarios.
Repeating some tests but sending data directly through the bus instead using /data endpoint.
This will give better testing support for hawkular scenarios.
Noted that with new changes on bus, using javax.jms packages are needed to connect remotely to bus destinations instead to use the old abstract hawkular-bus api.
=> HWKALERTS-121 Add integration tests for bus scenarios

hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/pom.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/main/java/org/hawkular/alerts/actions/email/EmailPlugin.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/main/java/org/hawkular/alerts/actions/email/EmailSessionProperties.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/java/org/hawkular/alerts/actions/email/CommonTest.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/java/org/hawkular/alerts/actions/email/JvmGarbageCollectionEmailTest.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/java/org/hawkular/alerts/actions/email/JvmHeapUsageEmailTest.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/java/org/hawkular/alerts/actions/email/JvmNonHeapUsageEmailTest.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/java/org/hawkular/alerts/actions/email/MultipleAllJvmEmailTest.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/java/org/hawkular/alerts/actions/email/SmtpServerTest.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/java/org/hawkular/alerts/actions/email/UrlAvailabilityEmailTest.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/java/org/hawkular/alerts/actions/email/UrlResponseTimeEmailTest.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/java/org/hawkular/alerts/actions/email/WebActiveSessionsEmailTest.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/java/org/hawkular/alerts/actions/email/WebContainerCurrentThreadsEmailTest.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/java/org/hawkular/alerts/actions/email/WebContainerPendingRequestsEmailTest.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/java/org/hawkular/alerts/actions/email/WebExpiredSessionsEmailTest.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/java/org/hawkular/alerts/actions/email/WebRejectedSessionsEmailTest.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/java/org/hawkular/alerts/actions/email/WebRequestsResponseTimeEmailTest.java, pom.xml
This PR moves the java.mail.Session to be managed via system properties.
This helps to configure from several points.
In alerts, it can be configured from hawkular-alerts.properties file, and in hawkular it can be configured in several places where system properties will be defined.
Also, it supports several definitions by tenant.
Other minor enhancements are to introduce an embedded smtp server for testing.
=> Email properties

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/json/GroupMemberInfo.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/json/UnorphanMemberInfo.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/DefinitionsService.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/DataDrivenGroupCacheManager.java, hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/PersistenceTest.java, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/TriggersITest.groovy, hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/TriggersHandler.java
- merge member-supplied context with group-supplied context
- allow members to provide tags at add-time.
- merge member-supplied tags with group-supplied tags
- allow members to provide member-level description
- allow the trigger name to default to the group name
Also
- fix a bug in adding members with a RateCondition
=> HWKALERTS-129 improve context and tag handling when adding a member trigger

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/trigger/Trigger.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/DefinitionsService.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassStatement.java, hawkular-alerts-engine/src/main/resources/hawkular-alerts-schema.cql
- persist the historical dataIdMappings used on member triggers
- use them when updating group conditions, supplementing any provided mappings
=> HWKALERTS-131 Re-use member dataIdMappings when updating group trigger conditions

hawkular-alerts-actions-plugins/hawkular-alerts-actions-aerogear/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-file/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-pagerduty/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-sms/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-snmp/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassCluster.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java, hawkular-alerts-rest/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, pom.xml
I have upgraded to parent 40 where it is defined the C* 3.4 dependency.
I fixed minimal changes to have itest running on C*.
Please @jshaughn, can you take a look ?
Some time without pushing so another pair of eyes are always welcome :-).
=> HWKALERTS-142 Minimal changes to upgrade to C* 3.4

examples/autoresolve-process/src/test/resources/autoresolve-process-definitions.json, examples/events/src/test/resources/events-tutorial-03.json, examples/events/src/test/resources/events-tutorial-04.json, examples/events/src/test/resources/events-tutorial-05.json, examples/hello-world/src/test/resources/hello-world-definitions.json, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/StandaloneAlerts.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsContext.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java, hawkular-alerts-rest-tests/pom.xml, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/ActionsITest.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/BusITest.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/ImportExportITest.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/TriggersITest.groovy, hawkular-alerts-rest-tests/src/test/wildfly-data/hawkular-alerts/alerts-data.json, hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/ActionsHandler.java, hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/AlertsHandler.java, hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/EventsHandler.java, hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/TriggersHandler.java
Highlights of this PR:
* Actions are validated against plugins:
- An action should have a plugins deployed in the system.
- An action should follow the properties defined in a plugin.
* Initialization files logic has been removed:
- As we have import/export logic, initialize the definitions via files was only used for some tests and had some caveats in clustering logic too, so I think that with the import/export we are covered for the same functionality and more consistency.
- Also it was problematic as plugins deployment needs the Engine fully deployed, so it should be moved in another place.
* The use case of what to do when a plugin is undeployed is not covered, now it maintains the action definitions but it will fail at the moment of execution of the action. Perhaps a nice to have is …
=> HWKALERTS-140 Validate actions definitions against plugins deployed

hawkular-alerts-rest-tests/pom.xml, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/AbstractITestBase.groovy
Main issue with ITests is that the server needs to initialize Cassandra scheme.
Sometimes (randomly) the first test is executed before the scheme is created.
This also might depends of several factors of the machine where tests are running.
So, I've tested several ways, but all of them are focus on increase the waiting time of the tests until everything is ready on the server.
This PR also increase the SMTP server to avoid some annoying but harmless errors on log.
=> Increase waiting time for C* in itest

hawkular-alerts-rest-tests/pom.xml, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/AbstractITestBase.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/IntegrationSuite.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/TenantITest.groovy, hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/TenantFilter.java
Improve common SMTP used on itests
SMTP server for itest can be improved if started shared for all tests in a suite.
This helps to reduce the waiting time.
Also, using a suite will help in future itest improvements, as at the beginning of the suite the waiting of cassandra scheme can be done.
Using a suite is compatible to exucute separate tests when needed.
=> Add global tenant validation on REST endpoints

examples/autoresolve-process/README.adoc, examples/autoresolve-process/src/test/groovy/create_definitions.groovy, examples/autoresolve-process/src/test/groovy/send_data.groovy, examples/events/README.adoc, examples/events/src/test/groovy/clean_events.groovy, examples/events/src/test/groovy/create_definitions_events_tutorial_03.groovy, examples/events/src/test/groovy/create_definitions_events_tutorial_04.groovy, examples/events/src/test/groovy/create_definitions_events_tutorial_05.groovy, examples/events/src/test/groovy/send_events_tutorial_01.groovy, examples/events/src/test/groovy/send_events_tutorial_02.groovy, examples/events/src/test/groovy/send_events_tutorial_03.groovy, examples/events/src/test/groovy/send_events_tutorial_04.groovy, examples/events/src/test/groovy/send_events_tutorial_05.groovy, examples/hello-world/README.adoc, examples/hello-world/src/test/groovy/create_definitions.groovy, examples/hello-world/src/test/groovy/send_data.groovy, examples/webhook/README.adoc, examples/webhook/src/test/groovy/create_definitions.groovy, examples/webhook/src/test/groovy/send_data.groovy
Minor PR to make compatible Hawkular Alerting examples with hawkular-services distribution.
Standalone scenario remains as it was but now examples can be easy executed against hawkular-services backend (helping to test the component).
Please @jshaughn, could you take a look ?
Thanks.
=> HWKALERTS-152 Update examples to work with hawkular-services

hawkular-alerts-actions-bus/src/main/java/org/hawkular/alerts/actions/bus/BusActionPluginListener.java, hawkular-alerts-actions-bus/src/main/java/org/hawkular/alerts/actions/bus/BusActionPluginSender.java
@PreDestroy methods can not throw custom Exception or a WARN will be filled on the log.
This is a minor refactor to clean some harmless warnings at startup.
Please @objectiser could you take a quick look ? 
Jay is on PTO for some days.
If you can mark it as review it I can merge it on the upstream.
Thanks a lot for your help :-)
=> HWKALERTS-154 Do not thrown Exception on BusActionPluginListener#close

README.adoc
"hawkular-alerts-bus-api" is listed twice in the list of modules
=> Readme: remove duplicated entry

hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/main/java/org/hawkular/alerts/actions/email/EmailTemplate.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/main/java/org/hawkular/alerts/actions/email/PluginMessageDescription.java
Locale should be forced to English (rather that system default) since the whole mail is written in English.
Without it, we could end up with mixed languages/formatting such as "GC Duration greater than 1000,0 ms" with wrong decimal separator.
Note that the issue was seen from JUnit EmailTemplateTest:
Expected :Tiny template: Alert [open] message: GC Duration greater than 1000,0 ms for App Server thevault~Local
Actual   :Tiny template: Alert [open] message: GC Duration greater than 1000.0 ms for App Server thevault~Local
=> Force English locale in mail decimal formatting

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/TriggerConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/dampening/Dampening.java, hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/engine/rules/ConditionMatch.drl, hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/RulesEngineTest.java
This PR groups the processing of ConditionEval inside the rules engine.
For multiple conditions triggers there are some corner cases that may lead to false satisfied status.
For example, given the following trigger:
Trigger1. Matching ANY
Condition1: HeapUsed < 10 
Condition2: HeapUsed > 20
Default dampening
Incoming data:
t1.	HeapUsed = 9
(CE = ConditionEval)
CE: c2. HU (9) > 20 [False]
** Update Dampening
CurrentEvals: 1) None
2) 9 > 20 [F] 
CE: c1. HU (9) < 10 [True]
** Update Dampening
CurrentEvals: 1) 9 < 10 [T]
2) 9 > 20 [F]
--> EVENT
t2. HeapUsed = 11
CE: c2. HU (11) > 20 [False]
** Update Dampening
Current Evals: 1) 9 < 10 [T]
2) 11 > 20 [F]
--> EVENT (INCORRECT)
t3. HeapUsed = 21
t4. HeapUsed = 19
Or this other example:
Trigger1. Matching ALL
Conditions 
"myapp.war" text == …
=> HWKALERTS-157 Process ConditionEval grouped per trigger

hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/init/CacheManager.java, pom.xml
It seems that ISPN can handle non-serialized objects.
This has created some problems when using MetricId as a key on ISPN between Metrics and Alerting.
A preliminar workaround was to use a string type as a key, but a better approach is to use a MetricId which implements Serialized.
This PR is on hold until we can test that a serialized MetricId class is working fine in metrics.
Then we will use that for key on published cache.
=> Upgrade MetricsId serialized class for ISPN uses

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/event/Alert.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/AlertsCriteria.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassStatement.java, hawkular-alerts-engine/src/main/resources/hawkular-alerts-schema.cql, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/AlertsITest.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/LifecycleITest.groovy, hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/AlertsHandler.java
This PR covers:
- Store lifecycle history on alert.
- Extend alerts criteria to support filtering on resolved and ack timestamps.
- Include new changes on alerts criteria on REST handlers.
=> HWKALERTS-161 Filter alerts by resolved and ack timestamps

hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/main/java/org/hawkular/alerts/actions/email/EmailPlugin.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/main/resources/template.html.default_en_US.ftl, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/main/resources/template.plain.default_en_US.ftl, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/resources/template.html.default_en_US.ftl, hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/test/resources/template.plain.default_en_US.ftl, hawkular-alerts-actions-plugins/hawkular-alerts-actions-file/src/test/java/org/hawkular/alerts/actions/file/FilePluginTest.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/CommonData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/JvmGarbageCollectionData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/JvmHeapUsageData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/JvmNonHeapUsageData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/MultipleAllJvmData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/UrlAvailabilityData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/UrlResponseTimeData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/WebActiveSessionsData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/WebContainerCurrentThreadsData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/WebContainerPendingRequestsData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/WebExpiredSessionsData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/WebRejectedSessionsData.java, hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/src/main/java/org/hawkular/alerts/actions/tests/WebRequestsResponseTimeData.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/event/Alert.java, hawkular-alerts-api/src/test/java/org/hawkular/alerts/api/JsonTest.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/LifecycleITest.groovy
This PR drops the old resolved* and ack* fields with new lifecycle list on Alert.
This change is propagated into actions architecture and plugins.
=> HWKALERTS-164 Unify resolved and ack fields with lifecycle

hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/ClusterITest.groovy
Minor one that escaped to the clustering tests.
=> Remove unused action for clustering tests

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/data/CacheKey.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/cache/CacheClient.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/cache/CacheManager.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java, hawkular-alerts-rest/deployments/hawkular-alerts-rest-metrics/src/main/webapp/WEB-INF/web.xml, hawkular-alerts-rest/deployments/hawkular-alerts-rest-services/src/main/webapp/WEB-INF/web.xml, hawkular-alerts-rest/deployments/hawkular-alerts-rest-standalone/src/main/webapp/WEB-INF/web.xml
- maintain the publish cache but makes alerting its client (as
opposed to metrics, for example).
- simplify CacheManager and CacheKey to be based only on tenantId
and dataId.
- perform global front-line filtering in AlertsService, as Data and
Events come into the system.
- optimize the engine to use the node-specific AlertsEngineCache
only in distributed deployment.  With global front-line filtering the
node-specific filtering is redundant in the single node use case.
* sorry for some formatting changes, eclipse seems to be struggling with
some of the long stream and lambda stuff.
=> [WIP] HWKALERTS-169 Global front-line filtering

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/cache/CacheManager.java
The filtering of ExternalCondition dataIds was valid when we were filtering inside Hmetrics, because the ids were not metrics-based, but it is not valid to filter out all ExternalCondition dataIds now that
we're doing front-line filtering.
@lucasponce Please review and merge.
=> HWKALERTS-173

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/StatusService.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassCluster.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/PartitionManagerImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/StatusServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/service/PartitionManager.java, hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/StatusHandler.java
Refactor Status logic to have its own service
Basically two things on this PR:
- To have a proper StatusService on the impl, before that the status endpoint was calculated by a simple DefinitionsService call, StatusService might hide and encapsulate other future complex checks.
- Add clustering info on status endpoint.
=> HWKALERTS-181 Add clustering information on status endpoint

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/json/JacksonDeserializer.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/Condition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/MissingCondition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/MissingConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/event/Event.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassStatement.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/util/MissingState.java, hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/engine/rules/ConditionMatch.drl, hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/schema/checker.cql, hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/schema/updates/schema-1.2.3.groovy, hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/RulesEngineTest.java, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/EventsLifecycleITest.groovy
As described in HWKALERTS-176 this PR implements a new type of condition: MissingCondition.
The purpose of this type is the ability to alert when a data/event has not been received into the system.
Some use cases (when metrics are involved) can be handled via ExternalCondition and Alerter add-ons, others simply not.
This enhancement fills that gap.
Main use case is the ability to respond to "Do I have received an event for this ? If not, alert".
The implementation details basically maintains a timer state when this condition is active resetting when new Events or Data arrives.
=> HWKALERTS-176 Add support for MissingConditions

hawkular-alerts-engine/pom.xml
These two transitive deps do not seem to be needed at build time or runtime, so they should
be excluded from the build and the distribution war files.
=> [HWKALERTS-183] Remove xmlpull and xpp3

pom.xml
This transitively updates the c* and driver version's to 3.0.9 and 3.0.5, respectively.
@lucasponce It looks like we'll need to update to the latest commons to match Hservices infrastructure (c* driver version).  We'll probably need a release fairly soon, to allow for Hmetrics to do the same.  Either a 1.3.x or a 1.4.0 version, we can discuss which one we prefer.
cc @stefannegrea
=> Move to commons 0.8.0 and match parent pom version. 

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/DefinitionsEvent.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/cache/CacheManager.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/DataDrivenGroupCacheManager.java
- batch update requests if the cache is already updating
- add more context to definition change events
- note, unused now but I did the work and it doesn't
hurt anything. So, I think we may as well keep it.
=> HWKALERTS-191 Prevent excessive cache updates

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/DroolsRulesEngineImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/IncomingDataManagerImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/service/RulesEngine.java
Splitting min-reporting-interval config as Data and Events scenarios could be very different.
So it makes sense to configure them by separate.
=> HWKALERTS-193 Split min-reporting-interval config

hawkular-alerts-rest/deployments/hawkular-alerts-rest-metrics/src/main/webapp/WEB-INF/classes/hawkular-alerts.properties, hawkular-alerts-rest/deployments/hawkular-alerts-rest-services/src/main/webapp/WEB-INF/classes/hawkular-alerts.properties, hawkular-alerts-rest/deployments/hawkular-alerts-rest-standalone/src/main/webapp/WEB-INF/classes/hawkular-alerts.properties
- move from engine jar to war dists such that defaults can be
modified more easily for different distributions.
- disable data-driven group triggers for metrics and services
distributions, because the primary use case is data forwarded
from metrics, and that Data will not have 'source' field values.
=> HWKALERTS-197 move hawkular-alerts.properties

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/DefinitionsEvent.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/cache/CacheManager.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java, hawkular-alerts-filter-api/src/main/java/org/hawkular/alerts/filter/CacheClient.java, hawkular-alerts-rest-tests/pom.xml, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/LifecycleITest.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/PerfCrudITest.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/PerfImportITest.groovy, hawkular-alerts-rest-tests/src/test/resources/domain.xsl, hawkular-alerts-rest-tests/src/test/resources/standalone-ha.xsl, hawkular-alerts-rest-tests/src/test/resources/standalone-hawkular.xsl, hawkular-alerts-rest-tests/src/test/resources/standalone.xsl, hawkular-alerts-rest/deployments/hawkular-alerts-rest-metrics/src/main/webapp/WEB-INF/web.xml, hawkular-alerts-rest/deployments/hawkular-alerts-rest-services/src/main/webapp/WEB-INF/web.xml, hawkular-alerts-rest/deployments/hawkular-alerts-rest-standalone/src/main/webapp/WEB-INF/web.xml
HWKALERTS-196 Improve perf examples for CRUD scenarios
This PR implement some enhancements on the CacheManager algorithm.
In an initial step, it fetches from backend the triggersIds/dataIds relation.
Using listeners, it maintains a triggerId -> dataIds relation used to update the published cache.
Now, the published cache holds a dataIds -> triggerIds relation.
On this way, we can maintain multiple references on N:M dataIds:triggerIds.
Improvements are good, PerfCrudITest shows that penalties queries have been minimized.
Please @jshaughn, let's start looking at this PR.
Note that I focus on the CacheManager only.
I will the DataDrivenGroupCacheManager in an following PR.
But I think we can review this one.
=> HWKALERTS-199 Improve CacheManager updates

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/data/Data.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/event/Event.java
- add in tenantId and dataSource, otherwise we may defer an
event that should have been sent to the engine.
- also: change natural ordering of Alert to be analogous to Event.
This is a micro-optimization, Because Data.id is more discriminating
that tenantId or source, there will be less String matching
when sorting.
=> HWKALERTS-203 Fix issue in Event.compareTo

hawkular-alerts-actions/hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/hawkular-alerts-actions-email-plugin/src/main/java/org/hawkular/alerts/actions/email/EmailPlugin.java, hawkular-alerts-actions/hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/hawkular-alerts-actions-email-plugin/src/test/java/org/hawkular/alerts/actions/email/SmtpSecureTest.java, hawkular-alerts-actions/hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/hawkular-alerts-actions-webhook-plugin/src/main/java/org/hawkular/alerts/actions/webhook/WebHookPlugin.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/ActionsITest.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/TriggersITest.groovy
- Fixing bug to let properties with suffixes (used in email plugin for properties on lifecycle state or localization).
- Unifying all properties used on email at plugin level. Originally email server was configured at system properties only, now both approaches are merged taking priority configuration at plugin level.
- Adding security support.
=> Unify email properties

hawkular-alerts-actions/hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/hawkular-alerts-actions-email-plugin/src/main/java/org/hawkular/alerts/actions/email/PluginMessageDescription.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/json/JacksonDeserializer.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/Condition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/NelsonCondition.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/NelsonConditionEval.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/event/Alert.java, hawkular-alerts-api/src/test/java/org/hawkular/alerts/api/JsonTest.java, hawkular-alerts-engine/pom.xml, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassStatement.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/util/NelsonData.java, hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/engine/rules/ConditionMatch.drl, hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/schema/updates/schema-1.5.0.groovy, hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/RulesEngineTest.java, hawkular-alerts-engine/src/test/resources/hawkular-alerts.properties, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/ConditionsITest.groovy, pom.xml
- Introduce a new native condition type, NelsonCondition. This
condition uses "Nelson Rules" to detect "out-of-control" metric
behavior.  The condition establishes baseline metric behavior
based on a configurable metric sample (mean, stdDev) and uses the
baseline to perform analysis on the incoming measurements.
- Introduces apache math3 dep for engine
- Introduce new activeRules field in conditions table
Also:
- fixes for HWKALERTS-208 because I was already adding some  new condition support...
- Fix bug with MISSING conditions in group trigger support
- improve the toString for Alert
- add some missing test support for a couple of condition types
@lucasponce, please review at your leisure. We can talk about it off-PR as well, if it makes sense.
=> HWKALERTS-209 NelsonRules

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java, hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/TriggersHandler.java
When updating trigger dampening (also for a group trigger) with a wrong triggerId, the `getCleanDampening()` would generate a wrong dampening.
In addition, in the case of missing DampeningId or TriggerId, only the DampeningId is mentioned in the Bad Argument HTTP error message. This change also suggests a missing TriggerId.
fixes: https://issues.jboss.org/browse/HWKALERTS-215
=> Dampening update: set correct TriggerId to dampening object

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassCluster.java, hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/schema/checker.cql
There was a bug in the initScheme() logic that prevented to apply properly the schema changes.
As commented in the JIRA, no possibility to replace bootstrap.groovy, as we have current system in production.
I have tested the bug manually with an external C*:
- Installing an Alerting 1.3.3.Final scheme.
- Upgrading an Alerting 1.5.x scheme.
So, cassalog tables look correct:
```
cqlsh> select * from hawkular_alerts.cassalog ;
bucket | revision | applied_at               | author | description | hash                                       | tags      | version
--------+----------+--------------------------+--------+-------------+--------------------------------------------+-----------+--------------
0 |        0 | 2017-01-31 16:14:56+0000 |   null |        null | …
```
=> HWKALERTS-220 Fix Schema upgrade logic

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java
@jshaughn I have splitted the HWKALERTS-218 in order to introduce the priorities changes in 1.5.1.Final.
This one is important as some events tests on cluster were broken due this bug.
=> HWKALERTS-221 Fix Events propagation on cluster environments

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/action/TimeConstraint.java, hawkular-alerts-api/src/test/java/org/hawkular/alerts/api/TimeConstraintTest.java
Let clients specify a time zone for the TimeConstraint such that
timestamp checks are performed against a predictable TZ as opposed to
the server default TZ.
@lucasponce Please review.
=> HWKALERTS-237 TimeConstraint needs to support the target time zone

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/DefinitionsListener.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/cache/PublishCacheManager.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsContext.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java
Please @jshaughn, could you take a look on this ?
There were a missing unordered set and this could cause potentially problems.
```
2017-03-24 17:08:30,816 DEBUG [org.hawkular.alerts.engine.impl.AlertsContext] (default task-3) Notifying applicable listeners 
{
org.hawkular.alerts.engine.cache.PublishCacheManager$$Lambda$315/339771229@4859fd80=[TRIGGER_CONDITION_CHANGE, TRIGGER_REMOVE], 
org.hawkular.alerts.engine.cache.ActionsCacheManager$$Lambda$314/196075570@3237d86d=[ACTION_DEFINITION_CREATE, ACTION_DEFINITION_REMOVE, ACTION_DEFINITION_UPDATE]
} of events 
[
DefinitionsEvent{type=ACTION_DEFINITION_REMOVE, targetTenantId='my-organization', targetId='notify-to-admins', dataIds=null, actionPlugin='email', actionDefinition=null, tags=null}, 
DefinitionsEvent{type=ACTION_DEFINITION_CREATE, …
```
=> HWKALERTS-243 Ensure DefinitionsEvents are notified to listeners in order

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/paging/AlertComparator.java, hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/AlertsCriteria.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/cache/PublishCacheManager.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassStatement.java, hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/schema/updates/schema-1.6.0.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/ActionsITest.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/AlertsITest.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/CrossTenantITest.groovy, hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/AlertsHandler.java, hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/CrossTenantHandler.java, hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/EventsHandler.java, hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/StreamWatcher.java
- Add support for filtering alerts by stime field without requiring status
- Introduce a REST stream watchers feature for alerts and events
- Make this feature available for crosstenant operations
I have started two approaches for this feature, a preliminar one (available here https://github.com/lucasponce/hawkular-alerts/tree/watchers-support-without-polling) uses a listener directly from the engine. This one has the advantages that does not require quering the backend, and that seemed a nice approach at the beginning. After some development, I realized that ensuring an ordered timeline could be more complex, as the asynchornous nature of our distributed design. So, I started this second approach which I think it is also interesting, as it offers to watch alerts and events in a timeline. …
=> HWKALERTS-236 Watchers for events and alerts

examples/elasticsearch/README.adoc, examples/elasticsearch/create-definitions.sh, examples/elasticsearch/create-logs.sh, examples/elasticsearch/elasticsearch-triggers.json, hawkular-alerters/hawkular-elasticsearch-alerter/hawkular-elasticsearch-alerter-lib/src/main/java/org/hawkular/alerter/elasticsearch/ElasticsearchAlerter.java, hawkular-alerters/hawkular-elasticsearch-alerter/hawkular-elasticsearch-alerter-lib/src/main/java/org/hawkular/alerter/elasticsearch/ElasticsearchQuery.java, hawkular-alerters/hawkular-elasticsearch-alerter/hawkular-elasticsearch-alerter-lib/src/test/java/org/hawkular/alerter/elasticsearch/ElasticsearchQueryTest.java, hawkular-alerts-actions/hawkular-alerts-actions-plugins/hawkular-alerts-actions-elasticsearch/hawkular-alerts-actions-elasticsearch-plugin/src/main/java/org/hawkular/alerts/actions/elasticsearch/ElasticSearchPlugin.java
HWKALERTS-251 Fix wrong dot character on Elasticsearch alerter
HWKALERTS-247 Add an Elasticsearch intergation example
Please @jshaughn, could you review ?
This would be necessary for a potential 1.6.x. and metrics 0.26.x.
=> HWKALERTS-252 Fix wrong nanoseconds parsed time

examples/elasticsearch/Dockerfile, examples/elasticsearch/README.adoc
Hi guys!
I converted the elasticsearch tutorial to a docker container.
Run the tutorial as docker container by the following commands
```
docker build -t hawkular-alerts-elasticsearch .
docker run -i -t  hawkular-alerts-elasticsearch /bin/bash
nohup /opt/hawkular-alerts/hawkular-alerts-rest-tests/target/wildfly-10.0.0.Final/bin/standalone.sh > hawkular-alerts.out 
nohup /opt/elasticsearch/bin/elasticsearch -Des.insecure.allow.root=true > elastic-search.out 
nohup /opt/kibana/bin/kibana > kibana.out 
/opt/create-definitions.sh
/opt/create-logs.sh
```
Best Regards!
Guilherme Baufaker Rêgo
=> ElasticSearch Tutorial as Docker Container

hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/AbstractITestBase.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/AlertsITest.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/CORSITest.groovy, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/EventsITest.groovy, hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/ActionsHandler.java, hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/AlertsHandler.java, hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/CrossTenantHandler.java, hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/EventsHandler.java, hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/QueryParamValidation.java, hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/RequestUtil.java, hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/ResponseUtil.java, hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/TriggersHandler.java
This is just a POC for the validation part of the issue.  In this approach we'd apply a new check to the endpoints we want to protect.  Note, if a client includes the 'ignoreUnknownQueryParams' query param, the check will always pass, making it possible for a client to override if the need arises.
Here I am applying it to just one endpoint, the alerts criteria search.
@lucasponce take a look when you have a moment.
=> HWKALERTS-239

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/DefinitionsService.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/cache/PublishCacheManager.java, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java, hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/TriggersHandler.java
A couple of related problems fixed here:
- remove deprecated java API add/remove/updateCondition
- internal use caused some problems, just kill them
- avoid unnecessary cache updates in publishCacheManager
- add setAllConditions() to java API
- avoids multiple notifications
- ensures all dataids for a trigger (both modes) are correctly cached
@lucasponce please review. The problems here were subtle, they hit me only intermittently after I had made a change to the metrics alerter's notification listener and "refresh" code.
=> HWKALERTS-262 Fix notification issues when setting conditions

api/pom.xml, api/src/main/java/org/hawkular/alerts/api/model/action/ActionDefinition.java, api/src/main/java/org/hawkular/alerts/api/model/action/TimeConstraint.java, api/src/main/java/org/hawkular/alerts/api/model/dampening/Dampening.java, api/src/main/java/org/hawkular/alerts/api/model/event/Alert.java, api/src/main/java/org/hawkular/alerts/api/model/event/Event.java, api/src/main/java/org/hawkular/alerts/api/model/trigger/Trigger.java, api/src/main/java/org/hawkular/alerts/api/model/trigger/TriggerAction.java, commons/src/main/resources/alerting-local.xml, engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImpl.java, engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImpl.java, engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/model/IspnActionDefinition.java, engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/model/IspnActionPlugin.java, engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/model/IspnEvent.java, engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/model/IspnTrigger.java, engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/model/TagsBridge.java, engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImplTest.java, engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImplTest.java
As follow up of https://github.com/hawkular/hawkular-alerts/pull/336 I prepared this PR.
It moves the indexes annotation into the impl package, so api does not need to have visibility of them.
Also, continue with the discussion, we can store copies on the backend, two reasons: make idempotent the objects stored in the backend cache and simplify the indexes on polimorphics classes to avoid workarounds of ispn-objectfilter package.
@jshaughn I think this is in good shape to merge and it will simplify the work on the Conditions side.
From me I will continue with the queries for Alerts/Events.
=> Move Indexes to impl details

engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImpl.java, engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnExpressionTagQueryParser.java, engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/model/IspnEvent.java, engine/src/main/java/org/hawkular/alerts/engine/tags/ExpressionTagQueryParser.java, engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImplTest.java
I am working in the tagQuery which is one of the difficult criterias.
Hopefully the backend supports all usecases and it is a change of design, just creating a proper query.
I am doing this in iterative steps, I want to consolidate this in .next.
@jshaughn can you merge ? thanks
=> Adapt tagQuery parser to Ispn syntax

.travis.yml, hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/tags/ExpressionTagQueryParser.java, hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/PersistenceTest.java, hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/tags/ExpressionTagQueryParserTest.java, hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/EventsITest.groovy
This is a fix to support spaces inside tagQuery regexp.
It was spotted by @josejulio for 1.6.x version.
It is first fixed in master but I can port this into the 1.6.x branch and prepare a release there if necessary.
There is a workaround (not using spaces), to I let @josejulio decide which approach works better for his needs.
=> HWKALERTS-270 TagQuery does not support empty spaces on regexp values

api/src/main/java/org/hawkular/alerts/api/model/trigger/Trigger.java
This fixes a bad bug on the engine.
When server is shutdown and restarted, transient fields are not serialized (which is intended), but in the Trigger(Trigger) constructor some missing default values where carried over the engine, throwing a non expected NPE.
=> Add default values for match/mode when Trigger is loaded from Ispn

examples/elasticsearch/README.adoc, examples/prometheus/README.adoc, examples/prometheus/alertmanager.yml, examples/prometheus/create-definitions.sh, examples/prometheus/prometheus-alerts.rules, examples/prometheus/prometheus-triggers.json
Add an example for the Prometheus Alerter.
It would be nice to have also a section in the docs like the Elasticsearch one.
An example of integration between P8S and ES would be great.
=> Add an Prometheus Alerter example

.travis.swagger.sh, rest-handlers/pom.xml
In .next I disabled docgen until we have migrated the API doc.
Now, travis should handle v1 and v2 versions.
Once these files are in the repository, we need to create a proper v1/v2 entries in the doc.
=> Enable docgen for v2 from travis

pom.xml
- Multiple activeByDefault properties with other activation profiles disable the expected profiles
mvn clean install didn't work by default and Travis CI was working with an empty profile as it showed green results this escaped from previous review.
=> Fix broken pom.xml

.travis.yml, dist/hawkular-alerts-openshift.yml, itests/src/test/groovy/org/hawkular/alerts/rest/EventsITest.groovy
Hi @jshaughn and @lucasponce.
Based on @jmazzitelli k8s template, I created a openshift templated
I think we can use that template to some testing under openshift. On the future, we can create a setup running some of the hawkular-alerts integration running on openshift such as Kafka, Prometheus, Gnocci, etc.
=> Openshift template

alerters/alerters-plugins/alerters-gnocchi/pom.xml, alerters/alerters-plugins/alerters-gnocchi/src/main/java/org/hawkular/alerter/gnocchi/GnocchiAlerter.java, alerters/alerters-plugins/alerters-gnocchi/src/main/java/org/hawkular/alerter/gnocchi/GnocchiQuery.java, alerters/alerters-plugins/alerters-gnocchi/src/test/java/org/hawkular/alerter/gnocchi/GnochiQueryTest.java, alerters/alerters-plugins/alerters-gnocchi/src/test/resources/log4j2.xml, alerters/alerters-plugins/pom.xml, dist/pom.xml, examples/gnocchi/README.adoc, examples/gnocchi/create-definitions.sh, examples/gnocchi/gnocchi-triggers.json, itests/pom.xml
Background
Hawkular Alerting is a federated alerting engine. Today it offers a REST API to integrate with any system and a set of pre-built integrations with Elasticsearch, Prometheus and Apache Kafka.
This PR adds Gnocchi into the alerter plugins.
In the context of the discussion
https://github.com/gnocchixyz/gnocchi/issues/71
We commented that we could add a poll alerter as a first step to cover Gnocchi and collect requeriments.
If the features Hawkular Alerting offers are interesting we can propose a fully streaming approach being Gnocchi owner to send data into Hawkular Alerting.
Anyway, this is just a first step to add alerting capabilities into Gnocchi.
cc @seuf @chungg @sileht @jd
=> Gnocchi Alerter

rest-handlers/src/main/rest-doc/generate-api.groovy
Change hasProperty to containsKey to get all the methods printed in the documentation for same path.
=> [HWKALERTS-287 REST-API is missing multiple methods for same path 

itests/src/test/groovy/org/hawkular/alerts/rest/TriggersITest.groovy, rest-handlers/src/main/java/org/hawkular/alerts/handlers/TriggersHandler.java
Proposal to make REST-API more consistent.
Change orphan/unorphan triggers to follow PUT as they should behave like idempotent methods. Update is already PUT method and these should be for that reason too.
=> Triggers API: Orphan/Unorphan to use PUT instead of POST

pom.xml
This brings hawkular alerts in sync with hawkular services version 0.40.x
=> [HWKALERTS-290] upgrade hawkular-commons 0.9.2->0.9.7
