hawkular/hawkular-alerts

hawkular-notifiers-email/src/main/java/org/hawkular/notifiers/email/notifications/EmailListener.java
hawkular-notifiers-email/src/main/test/org/hawkular/notifiers/email/notifications/EmailListenerTest.java

Initial implementation.
The PR is not ready yet.
I don't know how I can get configuration information for the EmailListener:
- from address
- to address

HWKALERTS-3 Implement an Email notification sender

---

README.adoc
hawkular-alerts-rest/pom.xml
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/CorsFilter.java
hawkular-alerts-rest/src/main/xsl/apiout2docbook.xsl
hawkular-alerts-rest/src/main/xsl/apiout2html.xsl
hawkular-alerts-rest/src/main/xsl/apiout2html_overview.xsl
pom.xml

Adding a CORS filter in the same way that Inventory and Metrics has done.

Adding a CORS filter for REST endpoints

---

.travis.build.bus.sh
.travis.maven.settings.xml
.travis.yml

These files are needed to activate Travis support

Add Travis config files

---

hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/NotifiersHandler.java
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/TriggersHandler.java
hawkular-alerts-rest/src/test/groovy/org/hawkular/alerts/rest/FlowUITest.groovy

This PR has an small fix for REST end point.

Fix for REST endpoint

---

.travis.yml
hawkular-actions-plugins/hawkular-actions-aerogear/pom.xml
hawkular-actions-plugins/hawkular-actions-aerogear/src/main/java/org/hawkular/actions/aerogear/listener/AerogearListener.java
hawkular-actions-plugins/hawkular-actions-aerogear/src/main/java/org/hawkular/actions/aerogear/registration/RegistrationInit.java
hawkular-actions-plugins/hawkular-actions-aerogear/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
hawkular-actions-plugins/hawkular-actions-aerogear/src/main/webapp/WEB-INF/jboss-web.xml
hawkular-actions-plugins/hawkular-actions-aerogear/src/main/webapp/WEB-INF/web.xml
hawkular-actions-plugins/hawkular-actions-aerogear/src/test/java/org/hawkular/actions/aerogear/listener/AerogearListenerTest.java
hawkular-actions-plugins/hawkular-actions-aerogear/src/test/java/org/hawkular/actions/aerogear/listener/UnifiedMessageMatcher.java
hawkular-actions-plugins/hawkular-actions-sms/src/main/java/org/hawkular/actions/sms/listener/SmsListener.java
hawkular-actions-plugins/pom.xml
hawkular-alerts-engine/src/main/resources/hawkular-alerts/actions.data
hawkular-alerts-engine/src/main/resources/hawkular-alerts/triggers.data
hawkular-alerts-engine/src/test/resources/hawkular-alerts/actions.data
hawkular-alerts-engine/src/test/resources/hawkular-alerts/triggers.data
hawkular-alerts-rest-tests/src/test/wildfly-data/hawkular-alerts/actions.data
hawkular-alerts-rest-tests/src/test/wildfly-data/hawkular-alerts/triggers.data

Create an Aerogear sender plugin

HWKALERTS-33 Create an Aerogear sender plugin

---

hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/ActionsHandler.java
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/AlertsHandler.java
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/TriggersHandler.java

- Change a few response codes for consistent API

- Add response code swagger doco for rest api

---

hawkular-actions-plugins/hawkular-actions-pagerduty/pom.xml
hawkular-actions-plugins/hawkular-actions-pagerduty/src/main/java/org/hawkular/actions/pagerduty/listener/PagerDutyListener.java
hawkular-actions-plugins/hawkular-actions-pagerduty/src/main/java/org/hawkular/actions/pagerduty/registration/RegistrationInit.java
hawkular-actions-plugins/hawkular-actions-pagerduty/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
hawkular-actions-plugins/hawkular-actions-pagerduty/src/main/webapp/WEB-INF/jboss-web.xml
hawkular-actions-plugins/hawkular-actions-pagerduty/src/main/webapp/WEB-INF/web.xml
hawkular-actions-plugins/hawkular-actions-pagerduty/src/test/java/org/hawkular/actions/pagerduty/listener/PagerDutyListenerTest.java
hawkular-actions-plugins/pom.xml
hawkular-alerts-engine/src/main/resources/hawkular-alerts/actions.data
hawkular-alerts-engine/src/main/resources/hawkular-alerts/triggers.data
hawkular-alerts-engine/src/test/resources/hawkular-alerts/actions.data
hawkular-alerts-engine/src/test/resources/hawkular-alerts/triggers.data
hawkular-alerts-rest-tests/src/test/wildfly-data/hawkular-alerts/actions.data
hawkular-alerts-rest-tests/src/test/wildfly-data/hawkular-alerts/triggers.data

Tested with my PagerDuty account

HWKALERTS-4 Create a PagerDuty alert notification sender

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java

I think this small fix will help on JIRA HWKALERTS-58, but I couldn't test it on a large test.
@jshaughn please, can you test it ?
Thx

HWKALERTS-58 Canceling tasks on PreDestroy

---

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/trigger/Tag.java
hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/DefinitionsService.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassStatement.java
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/TriggersITest.groovy
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/TriggersHandler.java

- Add /alerts/triggers/tag rest endpoint
- Add SLSB support for triggers by tag query
- Store "" category instead of nulls
- Fix query SELECT_TAGS_TRIGGERS_ALL_BY_NAME

HWKALERTS-47 Add Rest query for triggers by tag

---

hawkular-actions-plugins/hawkular-actions-email/src/main/java/org/hawkular/actions/email/EmailPlugin.java
hawkular-actions-plugins/hawkular-actions-email/src/main/java/org/hawkular/actions/email/listener/EmailListener.java
hawkular-actions-plugins/hawkular-actions-email/src/main/java/org/hawkular/actions/email/registration/RegistrationInit.java
hawkular-actions-plugins/hawkular-actions-email/src/main/java/org/hawkular/actions/email/template/EmailTemplate.java
hawkular-actions-plugins/hawkular-actions-email/src/main/resources/template.html.default_en_US.ftl
hawkular-actions-plugins/hawkular-actions-email/src/main/resources/template.plain.default_en_US.ftl
hawkular-actions-plugins/hawkular-actions-email/src/test/java/org/hawkular/actions/email/listener/EmailListenerTest.java
hawkular-actions-plugins/hawkular-actions-email/src/test/java/org/hawkular/actions/email/templates/EmailTemplateTest.java
hawkular-actions-plugins/hawkular-actions-email/src/test/resources/template.html.default_en_US.ftl
hawkular-actions-plugins/hawkular-actions-email/src/test/resources/template.plain.default_en_US.ftl
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java

- Sending actions on ack and resolved states on alerts.
- Add support into email plugin to deal with multiple states.
- Improve email plugin to support hawkular 1 condition use cases and generic multiconditions alerts.
- Add improvements to templates mechanisms.

Hwkalerts 37

---

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/AlertsService.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassStatement.java
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/AlertsITest.groovy
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/LifecycleITest.groovy
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/AlertsHandler.java
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/TriggersHandler.java

- new endpoints
- delete: /alerts/<id>
- put: /alerts/delete <criteria>
- get: /alerts/alert/<id>

HWKALERTS-70 Add ability to delete alerts

---

hawkular-alerts-engine/pom.xml
hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/cassandra/EmbeddedCassandra.java
pom.xml

This PR fix the rest profile due C* 2.2.0 upgrade.
Standalone profile needs this PRs merged:
https://github.com/hawkular/hawkular-commons/pull/14
And version upgraded as well.

HWKALERTS-75 Fix for C* 2.2.0 upgrade in rest profile

---

hawkular-alerts-actions-api/src/main/java/org/hawkular/alerts/actions/api/ActionPluginSender.java
hawkular-alerts-actions-api/src/main/java/org/hawkular/alerts/actions/api/ActionResponseMessage.java
hawkular-alerts-actions-bus/src/main/java/org/hawkular/alerts/actions/bus/BusActionPluginSender.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-aerogear/src/main/java/org/hawkular/alerts/actions/aerogear/AerogearPlugin.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-aerogear/src/test/java/org/hawkular/alerts/actions/aerogear/AerogearPluginTest.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/main/java/org/hawkular/alerts/actions/email/EmailPlugin.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-file/src/main/java/org/hawkular/alerts/actions/file/FilePlugin.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-file/src/test/java/org/hawkular/alerts/actions/file/FilePluginTest.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-pagerduty/src/main/java/org/hawkular/alerts/actions/pagerduty/PagerDutyPlugin.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-pagerduty/src/test/java/org/hawkular/alerts/actions/pagerduty/PagerDutyPluginTest.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-sms/src/main/java/org/hawkular/alerts/actions/sms/SmsPlugin.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-sms/src/test/java/org/hawkular/alerts/actions/sms/SmsPluginTest.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-snmp/src/main/java/org/hawkular/alerts/actions/snmp/SnmpPlugin.java
hawkular-alerts-actions-standalone/src/main/java/org/hawkular/alerts/actions/standalone/MsgLogger.java
hawkular-alerts-actions-standalone/src/main/java/org/hawkular/alerts/actions/standalone/StandaloneActionPluginSender.java
hawkular-alerts-actions-standalone/src/main/java/org/hawkular/alerts/actions/standalone/StandaloneActionResponseMessage.java
hawkular-alerts-bus-api/src/main/java/org/hawkular/alerts/bus/api/BusActionResponseMessage.java
hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/listener/ActionPluginOperationListener.java
hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/log/MsgLogger.java

Add missing ActionPluginSender in plugins

Refactor OperationMessage into ActionResponseMessage

---

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/paging/AlertComparator.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java
hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/PersistenceTest.java

Minor PR but @jshaughn can you take a look on it ?

HWKALERTS-95 Support sorting on context in Alerts

---

hawkular-alerts-actions-api/src/main/java/org/hawkular/alerts/actions/api/Global.java
hawkular-alerts-actions-bus/src/main/java/org/hawkular/alerts/actions/bus/ActionPlugins.java
hawkular-alerts-actions-bus/src/main/java/org/hawkular/alerts/actions/bus/BusActionPluginListener.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/java/org/hawkular/alerts/actions/webhook/WebHookApp.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/java/org/hawkular/alerts/actions/webhook/WebHookHandler.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/java/org/hawkular/alerts/actions/webhook/WebHookPlugin.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/java/org/hawkular/alerts/actions/webhook/WebHooks.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/java/org/hawkular/alerts/actions/webhook/accounts/PersonaFilter.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/webapp-standalone/WEB-INF/jboss-deployment-structure.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/webapp-standalone/WEB-INF/jboss-web.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/webapp-standalone/WEB-INF/web.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/webapp/WEB-INF/jboss-web.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/webapp/WEB-INF/web.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/test/java/org/hawkular/alerts/actions/webhook/WebHooksTest.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/test/resources/log4j.properties
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/test/resources/test-webhooks.json
hawkular-alerts-actions-plugins/pom.xml

Preliminar version of WebHooks plugin.
Some goals for this PR:
- Introduction of Global annotation for plugins.
- Endpoints on plugin for webhooks management.
- Possibility to persist webhooks configuration into disk.

HWKALERTS-43 WebHooks plugin

---

hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/src/main/java/org/hawkular/alerts/actions/irc/IrcPlugin.java
hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/src/main/webapp-standalone/WEB-INF/jboss-deployment-structure.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/src/main/webapp-standalone/WEB-INF/jboss-web.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/src/main/webapp-standalone/WEB-INF/web.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/src/main/webapp/WEB-INF/jboss-web.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/src/main/webapp/WEB-INF/web.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/src/test/java/org/hawkular/alerts/actions/irc/IrcPluginTest.java
hawkular-alerts-actions-plugins/pom.xml
hawkular-alerts-rest-tests/pom.xml
pom.xml

Create a basic architecture to support IRC actions plugins

HWKALERTS-45 Add a basic IRC Action Plugin

---

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/EventCondition.java
hawkular-alerts-api/src/test/java/org/hawkular/alerts/api/EventConditionTest.java
hawkular-alerts-bus/pom.xml
hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/listener/AvailDataListener.java
hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/listener/CommandEventListener.java
hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/listener/MetricDataListener.java
pom.xml

Support for Hawkular-484, Deployment Failure Event Alerting

Deployment fail

---

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/json/JacksonDeserializer.java
hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/Condition.java
hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/RateCondition.java
hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/RateConditionEval.java
hawkular-alerts-api/src/test/java/org/hawkular/alerts/api/JsonTest.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassStatement.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/util/RateData.java
hawkular-alerts-engine/src/main/resources/hawkular-alerts-schema.cql
hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/engine/rules/ConditionMatch.drl
hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/RulesEngineTest.java
hawkular-alerts-engine/src/test/resources/hawkular-alerts/conditions-data.json
hawkular-alerts-engine/src/test/resources/hawkular-alerts/triggers-data.json

Add RateCondition to support thresholding against rate of change of a counter metric.

HWKALERTS-111 

---

hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/accounts/PersonaFilter.java
pom.xml

Upgrade to accounts 1.1.4.Final and commons 0.2.5.Final, both needed for release.
Upgrading the way persona is injected in a similar way as inventory does.

HWKALERTS-112 Upgrade commons and accounts

---

hawkular-alerts-rest/pom.xml
hawkular-alerts-rest/src/main/webapp/WEB-INF/web.xml
pom.xml

With this, the backend starts accepting tokens generated via Accounts, instead of only OAuth Bearer tokens and username/password.

HAWKULAR-877 - Enabled the Secret Store for the REST API

---

hawkular-alerts-bus/pom.xml
hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/listener/BusActionListener.java
pom.xml

@lucasponce could you please review and eventually merge?

151217 accounts 2.0.9.final

---

hawkular-alerts-rest-tests/pom.xml
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/AlertsITest.groovy
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/LifecycleITest.groovy
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/AlertsHandler.java
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/TriggersHandler.java

Make sure to fail on bad tag criteria syntax

HWKALERTS-108 Tag criteria issue

---

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/paging/AlertComparator.java
hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/paging/EventComparator.java
hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/paging/TriggerComparator.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java

- also, fix alert context ordering, don't keep state (contextKey) in an enum

HWKALERTS-96 Add context ordering for trigger and event fetch

---

README.adoc

Updating the profile and adding the missing component on the description.

Update proper profiles on readme

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java

Make sure actions are added to triggers fetched by criteria

---

hawkular-alerts-actions-bus/src/main/java/org/hawkular/alerts/actions/bus/BusActionPluginSender.java

This fix a warning that comes from the new bus migration infrastructure.
It was triggered on hawkular showing an annoying warning.
This issue is not present on intergation tests and I ran some manual tests on hawkular and it seems gone.

HWKALERTS-125 Close JMS cached connection on bus action plugin

---

hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/listener/BusActionListener.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsContext.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassActionsServiceImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/log/MsgLogger.java
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/AlertsITest.groovy
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/AlertsHandler.java

On this PR:
- Optimize Singleton beans.
- Initialize heavy tasks on separate thread.
- Fix warnings on bus usage.

Init separate thread

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java

- Don't overwrite name and description of existing members because
those could be customized at the member-level.
- Don't overwrite, instead only add new context or tag entries.
- Don't overwrite any stored dataIdMap info.

Group Trigger update fixes

---

examples/autoresolve-process/README.adoc
examples/autoresolve-process/pom.xml
examples/autoresolve-process/src/test/groovy/create_definitions.groovy
examples/autoresolve-process/src/test/groovy/send_data.groovy
examples/autoresolve-process/src/test/resources/autoresolve-process-definitions.json
examples/events/README.adoc
examples/events/pom.xml
examples/events/src/test/groovy/clean_events.groovy
examples/events/src/test/groovy/create_definitions_events_tutorial_03.groovy
examples/events/src/test/groovy/create_definitions_events_tutorial_04.groovy
examples/events/src/test/groovy/create_definitions_events_tutorial_05.groovy
examples/events/src/test/groovy/send_events_tutorial_01.groovy
examples/events/src/test/groovy/send_events_tutorial_02.groovy
examples/events/src/test/groovy/send_events_tutorial_03.groovy
examples/events/src/test/groovy/send_events_tutorial_04.groovy
examples/events/src/test/groovy/send_events_tutorial_05.groovy
examples/events/src/test/resources/events-tutorial-03.json
examples/events/src/test/resources/events-tutorial-04.json
examples/events/src/test/resources/events-tutorial-05.json
examples/hello-world/README.adoc
examples/hello-world/pom.xml
examples/hello-world/src/test/groovy/create_definitions.groovy
examples/hello-world/src/test/groovy/send_data.groovy
examples/hello-world/src/test/resources/hello-world-definitions.json

Moved the informal hawkular-examples into hawkular-alerts project.
Created a plain examples folder, more intuitive an easy to start.
Scripts moved from bash to groovy to run them from maven.
Json definitions extracted to external files.
Tested on standalone.

Hwkalerts 132 examples

---

hawkular-alerts-actions-plugins/hawkular-alerts-actions-aerogear/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-file/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-pagerduty/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-sms/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-snmp/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/trigger/FullTrigger.java
hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/trigger/Trigger.java
hawkular-alerts-api/src/test/java/org/hawkular/alerts/api/JsonTest.java
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/AbstractITestBase.groovy
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/TriggersITest.groovy
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/ActionPluginHandler.java
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/ActionsHandler.java
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/AlertsHandler.java
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/EventsHandler.java
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/ExportHandler.java
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/ImportHandler.java
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/ResponseUtil.java
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/TriggersHandler.java

HWKALERTS-135 Fix to add details on error codes
HWKALERTS-136 Fix for error on deployment of webhooks plugin

HWKALERTS-134 Fix for NPE on FullTrigger creation

---

hawkular-alerts-actions-plugins/hawkular-alerts-actions-aerogear/src/main/webapp/WEB-INF/web.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/src/main/webapp/WEB-INF/web.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-file/src/main/webapp/WEB-INF/web.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/src/main/webapp/WEB-INF/web.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-pagerduty/src/main/webapp/WEB-INF/web.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-sms/src/main/webapp/WEB-INF/web.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-snmp/src/main/webapp/WEB-INF/web.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/src/main/webapp/WEB-INF/web.xml
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/BusITest.groovy
hawkular-alerts-rest-tests/src/test/resources/application-roles.properties
hawkular-alerts-rest-tests/src/test/resources/application-users.properties
hawkular-alerts-rest/src/main/webapp/WEB-INF/web.xml

@jshaughn Fix for adding basic JAAS
Locally I had strange results on itest, probably due C* driver and some delay in the time the wildfly server is up and running and the tests start.
Let's see if travis can deal with it.

Add BASIC JAAS security to .war artifacts

---

.travis.yml
hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/CassPersistenceTest.java
hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/PersistenceTest.java

We put the PersistenceTests on the perf profile and with last changes (plugins validation, removal of init data and some adjustments on groups triggers) some issues were introduced.

Fixes for PersistenceTests

---

hawkular-alerts-actions-api/pom.xml
hawkular-alerts-actions-bus/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-aerogear/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-file/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-pagerduty/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-sms/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-snmp/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/pom.xml
hawkular-alerts-actions-plugins/pom.xml
hawkular-alerts-actions-standalone/pom.xml
hawkular-alerts-api/pom.xml
hawkular-alerts-bus-api/pom.xml
hawkular-alerts-bus/pom.xml
hawkular-alerts-engine/pom.xml
hawkular-alerts-metrics/pom.xml
hawkular-alerts-rest-tests/pom.xml
hawkular-alerts-rest/pom.xml
pom.xml

The pom update somehow did not happen after the 1.0.2.Final release.  Update to a snapshot of next release version.
@lucasponce Please review and merge.

Fix pom versions.

---

hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/PersistenceTest.java
hawkular-alerts-rest-tests/src/test/resources/standalone-hawkular.xsl
pom.xml

Update parent to 43
Similar as #185 but from a rebased master.

Update commons to 0.7.1.Final

---

README.adoc
examples/autoresolve-process/README.adoc
examples/autoresolve-process/pom.xml
examples/events/README.adoc
examples/events/pom.xml
examples/hello-world/README.adoc
examples/hello-world/pom.xml
hawkular-alerts-actions-api/pom.xml
hawkular-alerts-actions-bus/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-aerogear/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-file/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-irc/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-pagerduty/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-sms/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-snmp/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-tests/pom.xml
hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/pom.xml
hawkular-alerts-actions-plugins/pom.xml
hawkular-alerts-actions-standalone/pom.xml
hawkular-alerts-api/pom.xml
hawkular-alerts-bus-api/pom.xml
hawkular-alerts-bus/pom.xml
hawkular-alerts-engine/pom.xml
hawkular-alerts-metrics/pom.xml
hawkular-alerts-rest-tests/pom.xml
hawkular-alerts-rest/pom.xml
pom.xml

@lucasponce please review and merge

Minor - rebrand 'Hawkular Alerts' as 'Hawkular Alerting'

---

hawkular-alerts-actions-plugins/hawkular-alerts-actions-sms/pom.xml

@jshaughn another minor PR to review.

HWKALERTS-151 Bump twilio 6.x version for sms plugin

---

hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/AlertsHandler.java
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/EventsHandler.java
hawkular-alerts-rest/src/main/java/org/hawkular/alerts/rest/TriggersHandler.java

This PR fixes some broken layout on the REST hawkular.org doc like this one:
@jshaughn please, could you take a look ?
Thanks

HWKALERTS-153 Fix some issues on Swagger generated doc

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassCluster.java

Adding fine control on C* driver parameters.

Add additional Timeout parameters for C* driver at configuration level

---

hawkular-alerts-bus-api/pom.xml
hawkular-alerts-bus-api/src/main/java/org/hawkular/alerts/bus/api/DataIdPrefix.java
hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/init/CacheManager.java
hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/listener/AvailDataListener.java
hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/listener/MetricDataListener.java
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/BusITest.groovy

Please @jshaughn, can you review this patch ?
I will prepare a srcdeps with hawkular-services to fix & validate everything is working as expected.
Then we can release alerting and hawkular-services.
Thanks.

HWKALERTS-158 Prefix properly data back from the bus on HM integration

---

hawkular-alerts-bus/src/main/java/org/hawkular/alerts/bus/init/CacheManager.java
hawkular-alerts-rest-tests/pom.xml
hawkular-alerts-rest-tests/src/test/resources/standalone-hawkular.xsl

Minor one to enable additional debug logging on itest.

Logging for debugging itest scenarios

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/util/CompareData.java
hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/engine/rules/ConditionMatch.drl
hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/RulesEngineTest.java

- Now allows for the relevant Data to be reported at different times.
- Add new test and update existing test to use distinct times
- Also, null-protect some log stmts (although I'm not sure when log may
be null, perhaps in some test envs)

HWKALERTS-160 Change CompareCondition Handling

---

hawkular-alerts-api/src/test/java/org/hawkular/alerts/api/EventConditionTest.java

Minor one.
In the context of EventCondition I have added an additional test covering more complex expressions.

Additional unit tests for events

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/StandaloneAlerts.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassActionsServiceImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassCluster.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassClusterSession.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java
hawkular-alerts-engine/src/main/resources/hawkular-alerts-checker.cql
hawkular-alerts-engine/src/main/resources/hawkular-alerts-schema.cql
hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/CassPersistenceTest.java
hawkular-alerts-rest-tests/pom.xml

- Move from JVM singleton to container singleton
- Session injected through components
- Fix Shutdown method invoked on end of lifecycle
- Check when a schema is fully created to avoid race conditions on clustering environments

HWKALERTS-166 Refactor CassCluster component:

---

hawkular-alerts-rest/deployments/hawkular-alerts-rest-metrics/pom.xml
hawkular-alerts-rest/deployments/hawkular-alerts-rest-metrics/src/main/webapp/WEB-INF/jboss-deployment-structure.xml

Add C* dependencies on metrics deployment

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/PartitionManagerImpl.java

This PR adds a @PreDestroy call on PartitionManagerImpl removing listeners and doing an explicit stop on components.
This reduces errors on stopping servers on clustering environments.
Please @jshaughn this should be easy to review.
Thanks.

HWKALERTS-167 Handle shutdown on PartitionManager

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassCluster.java
hawkular-alerts-rest-tests/src/test/resources/domain.xsl
hawkular-alerts-rest-tests/src/test/resources/standalone-ha.xsl
hawkular-alerts-rest-tests/src/test/resources/standalone-hawkular.xsl
hawkular-alerts-rest-tests/src/test/resources/standalone.xsl

This PR adds additional protection on clustering scenarios.

Fix cluster schema creation

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassCluster.java

Please @jshaughn take a look on this.

HWKALERTS-171 Support SSL on Cassandra connections

---

hawkular-alerts-rest/deployments/hawkular-alerts-rest-metrics/src/main/webapp/WEB-INF/web.xml

The metrics distribution should be like standalone and not have security-constraints.
@lucasponce please review.

The metrics distribution should be like standalone

---

pom.xml

Upgrade freemarker and hawkular-commons to sync with other projects

Minor dep upgrades

---

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/AlertsService.java
hawkular-alerts-engine/pom.xml
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/cache/CacheManager.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java
hawkular-alerts-filter-api/pom.xml
hawkular-alerts-filter-api/src/main/java/org/hawkular/alerts/filter/CacheClient.java
hawkular-alerts-filter-api/src/main/java/org/hawkular/alerts/filter/CacheKey.java
pom.xml

- make injecting CacheClient easier by moving it and CacheKey to its own jar
- add ignoreFiltering option to sendData/Events to allow clients to
perform their own filtering and (java clients only for now)

hwkmetrics-507

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/DroolsRulesEngineImpl.java
hawkular-alerts-rest-tests/pom.xml
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/PerfSendITest.groovy

This improvement will help to not block Java clients as metrics that send directly data into the engine.

Add additional performance tests

---

hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/PerfRulesEngineTest.java

Added some convenience perf test utilities.

HWKALERTS-185 Extend perf scenarios for triggers with large # of conds.

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/IncomingDataManager.java

This is suggestion about how we can implement the same goal using the internal ManagedExecutorService.
It performs same tasks of the first approach with the benefits to not mix technologies.
Also, having the managed-executor-service at configuration level is useful.
Today we are using the default one, but a new one can be created at configuration level if necessary.
Detaulf one could be a good starting point, perf results can give more info to adjust the parameters.

Using Java EE concurrent resources

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/PartitionManagerImpl.java

The PartitionManager implementation was designed with a single listener per type.
But re-registering overwrite the previous listener and could create unexpected behaviors.
This should be addressed allowing multiple listeners as it is done on this PR.

Support for multiple listeners in PartitionManagerImpl

---

examples/autoresolve-process/README.adoc
examples/events/README.adoc
examples/hello-world/README.adoc
examples/webhook/README.adoc
hawkular-alerts-actions/hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/hawkular-alerts-actions-email-plugin/src/main/java/org/hawkular/alerts/actions/email/EmailPlugin.java
hawkular-alerts-actions/hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/deployments/hawkular-alerts-actions-webhook-standalone/src/main/webapp/WEB-INF/web.xml
hawkular-alerts-actions/hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/hawkular-alerts-actions-webhook-plugin/src/main/java/org/hawkular/alerts/actions/webhook/WebHookPlugin.java

Fix EmailPlugin to be Thunderbird friendly.
Fix message on Webhook plugin.
@jshaughn could you review this one ?
I would like to merge this one to have the examples in a good state before adding the new ones.
Thanks.

Fix documentation in current examples

---

examples/autoresolve-process/README.adoc
examples/events/pom.xml
examples/group-triggers/README.adoc
examples/group-triggers/pom.xml
examples/group-triggers/src/test/groovy/clean_all.groovy
examples/group-triggers/src/test/groovy/create_group_trigger.groovy
examples/group-triggers/src/test/groovy/create_members.groovy
examples/group-triggers/src/test/groovy/update_group_trigger.groovy
examples/group-triggers/src/test/resources/group-trigger-definitions.json
examples/group-triggers/src/test/resources/update-group-conditions.json
examples/hello-world/README.adoc
examples/webhook/README.adoc

Fixing some minor issues in the examples and adding a new one for groups handling.

Add examples for groups triggers handling

---

hawkular-alerts-actions/hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/hawkular-alerts-actions-email-plugin/src/main/java/org/hawkular/alerts/actions/email/EmailPlugin.java
hawkular-alerts-actions/hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/hawkular-alerts-actions-email-plugin/src/main/java/org/hawkular/alerts/actions/email/PluginMessageDescription.java
hawkular-alerts-actions/hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/hawkular-alerts-actions-email-plugin/src/main/resources/template.html.default_en_US.ftl
hawkular-alerts-actions/hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/hawkular-alerts-actions-email-plugin/src/main/resources/template.plain.default_en_US.ftl
hawkular-alerts-actions/hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/hawkular-alerts-actions-email-plugin/src/test/resources/template.html.default_en_US.ftl
hawkular-alerts-actions/hawkular-alerts-actions-plugins/hawkular-alerts-actions-email/hawkular-alerts-actions-email-plugin/src/test/resources/template.plain.default_en_US.ftl

Minor one.
Small fixes where combining events in the email plugin.
No functionalities changes.

HWKALERTS-192 Full support of Events on email plugin

---

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/DefinitionsListener.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/DataDrivenGroupCacheManager.java

- add ability to defer a set of notifications
- change listener callback to accept a set of notifications

HWKALERTS-195 Import should defer notifications to the end

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/cache/CacheManager.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java

- publishCache and publishDataIdsCache should work in atomic way

HWKALERTS-204 notifyListenersDeferred should filter correct events

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/StandaloneAlerts.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassAlertsServiceImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassCluster.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java
hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/PersistenceTest.java

This is still a POC not sure if it is ready for merging.
Testing and tweaking parameters are still in WIP.
But code can be reviewed.
Strategy is to batch those things that make sense, basically within same partition, and prioritizing aspects close to real use cases.
With this setup, -Dtest-env=perf and -Pperf-itest shows a 5% of improvements.
Anyway, I am still studying these changes and testing a good parametrization before to confirm any good result.

HWKALERTS-202 Introduce batch in several Insert/Update/Delete scenarios

---

hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/filter/CorsRequestFilter.java
hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/filter/CorsResponseFilter.java
hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/filter/OriginValidation.java
pom.xml

This is related to HWKMETRICS-554 (https://issues.jboss.org/browse/HWKMETRICS-554)

Use hawkular-commons 0.9.1, update CORS

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/PartitionManagerImpl.java

- Extend the modified entry events for the internal caches used to manage the PartitionManager logic
@jshaughn please take a look. If ok I will prepare proper PRs for master and 1.4.x branches.

HWKALERTS-210 Add missing events for PartitionManageImpl

---

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/json/JacksonDeserializer.java
hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ExternalCondition.java
hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/ExternalConditionEval.java
hawkular-alerts-api/src/test/java/org/hawkular/alerts/api/JsonTest.java
hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/engine/rules/ConditionMatch.drl
hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/RulesEngineTest.java

Extending the ExternalCondition to events.
Please @jshaughn, can you review it ?
Thanks.

HWKALERTS-207 Allow ExternalCondition to be fired on Event submission

---

hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/PerfImportITest.groovy
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/PerfSendITest.groovy

Adding more sequential tests to cover additional scenarios reported by QA.

Additional perf tests

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/GroupITest.groovy

HWKALERTS-216 Ensure disabled triggers are removed from the rulebase

---

examples/events-aggregation/README.adoc
examples/events-aggregation/pom.xml
examples/events-aggregation/src/test/groovy/create_definitions.groovy
examples/events-aggregation/src/test/groovy/send_events_fraud.groovy
examples/events-aggregation/src/test/groovy/send_events_loyalty.groovy
examples/events-aggregation/src/test/groovy/send_events_marketing.groovy
examples/events-aggregation/src/test/resources/fraud-definitions.json
examples/events-aggregation/src/test/resources/loyalty-definitions.json
examples/events-aggregation/src/test/resources/marketing-definitions.json
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/EventsAggregationExtensionITest.groovy

Fix a bug on EventsAggregationITest
@jshaughn this should be an easy PR.
It adds a new example to make more easy to start with the Extension/Alerter.

Add an user friendly Events Aggregation example

---

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/export/Definitions.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/ImportExportITest.groovy
hawkular-alerts-rest-tests/src/test/wildfly-data/hawkular-alerts/groups-data.json

This is an enhancement to create members from the import endpoint.

HWKALERTS-217 Support GroupMemberInfo on /import endpoint

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineCache.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassCluster.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/PartitionManagerImpl.java
hawkular-alerts-engine/src/test/java/org/hawkular/alerts/engine/impl/AlertsEngineCacheTest.java
hawkular-alerts-rest-tests/pom.xml
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/AbstractITestBase.groovy
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/ClusterIntegrationSuite.groovy
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/CrossTenantITest.groovy
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/EventsLifecycleITest.groovy
hawkular-alerts-rest-tests/src/test/resources/domain.xsl
hawkular-alerts-rest-tests/src/test/resources/host.xsl
hawkular-alerts-rest-tests/src/test/resources/standalone-ha.xsl

This PR extend the ITests coverage on cluster profile.
There is a known issue about listeners that is being addressed on HWKALERTS-223 but that will be sent in a separate PR.
This PR have the cluster profile stable.
Please @jshaughn, take a look. Thx.

Extend cluster itest

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassCluster.java
hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/schema/bootstrap.groovy
pom.xml

[PR 292](https://github.com/hawkular/hawkular-alerts/pull/292) should be merged before this PR.

[HWKALERTS-227] make bootstrap script handle shutdowns and restarts

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassCluster.java
hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/schema/bootstrap.groovy
hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/schema/updates/schema-1.2.3.groovy
pom.xml

HWKALERTS-220 Fix schema upgrade logic
HWKALERTS-222 Add cassalog verification checks
HWKALERTS-227 Make bootstrap script handle shutdowns and restarts

Backport on 1.3.x fixes for HWKMETRICS-594

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/TriggersITest.groovy
hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/TriggersHandler.java

A filter to ignore those conditions that does not match with the triggerMode specified as parameter.

HWKALERTS-229 Filter unmatching triggerMode conditions on set*Conditions

---

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/DefinitionsService.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/service/AlertsEngine.java
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/ActionsITest.groovy
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/CrossTenantITest.groovy
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/EventsLifecycleITest.groovy
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/GroupITest.groovy
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/LifecycleITest.groovy
hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/TriggersHandler.java

- new endpoints triggers/enabled and triggers/groups/enabled
- update existing itests to use new endpoints where applicable
- add new test

HWKALERTS-233 : Add trigger enable/disable to REST API

---

hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/util/MissingState.java
hawkular-alerts-engine/src/main/resources/org/hawkular/alerts/engine/rules/ConditionMatch.drl
hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/LifecycleITest.groovy

@lucasponce review por favor, gracias.

HWKALERTS-234 Apply current trigger mode to MissingState eval

---

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/Condition.java
hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/model/condition/NelsonCondition.java
hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/rest-doc/apidoc.groovy

@jshaughn a trivial PR to review.
Some adjustments to the parser to process correctly the values of the NelsonRule in the doc.

HWKALERTS-242 Missing swagger doc for NelsonCondition

---

hawkular-alerts-api/src/main/java/org/hawkular/alerts/api/services/DefinitionsListener.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/cache/PublishCacheManager.java
hawkular-alerts-engine/src/main/java/org/hawkular/alerts/engine/impl/CassDefinitionsServiceImpl.java

I needed to resolve a couple of conflicts as code differed from 1.6.x but I guess this is ready to merge on 1.5.x branc.
@jshaughn please, take a look, thanks.

HWKALERTS-243 Backport - DefinitionsEvents might have a wrong order

---

hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/AlertsHandler.java
hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/CrossTenantHandler.java
hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/EventsHandler.java

HWKALERTS-255 Fix tagQuery BNF

---

examples/tutorial/lessons/lesson-01-plumbing.adoc

@jshaughn  Following your tip ... 
i added the package in oder to execute tutorial!
This is a simple line on .adoc tutorial

OSX Tip for Tutorial

---

api/src/main/java/org/hawkular/alerts/api/services/DefinitionsService.java
engine/src/main/java/org/hawkular/alerts/engine/cache/PublishCacheManager.java
engine/src/main/java/org/hawkular/alerts/engine/impl/cass/CassDefinitionsServiceImpl.java
engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImpl.java
engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnPk.java
itests/src/test/groovy/org/hawkular/alerts/rest/AbstractITestBase.groovy
itests/src/test/groovy/org/hawkular/alerts/rest/AlertsITest.groovy
itests/src/test/groovy/org/hawkular/alerts/rest/EventsITest.groovy
rest-handlers/src/main/java/org/hawkular/alerts/handlers/TriggersHandler.java

@lucasponce This isn't quite done, I need to add tests but also there is a test failure that points out an issue that maybe you are aware of but caught me a little by surprise.  When doing something like:
backend.put(pk(trigger), trigger);
trigger.setId("flubber");
The Trigger object in the cache is actually modified.  This maybe should not be surprising, but it is dangerous and tripped me up.  We should discuss whether we want this behavior or whether we want to actually store copies.  As is we need to be very careful.
Anyway, if you want to merge this go ahead, and we can just fix things as we move forward.

Ispn condition

---

engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnPk.java
engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImplTest.java

- Tweak a test to ne considerate of in-memory map

- Update Condition PK to be consistent with the other.

---

api/src/main/java/org/hawkular/alerts/api/model/condition/AvailabilityCondition.java
api/src/main/java/org/hawkular/alerts/api/model/condition/CompareCondition.java
api/src/main/java/org/hawkular/alerts/api/model/condition/Condition.java
api/src/main/java/org/hawkular/alerts/api/model/condition/EventCondition.java
api/src/main/java/org/hawkular/alerts/api/model/condition/ExternalCondition.java
api/src/main/java/org/hawkular/alerts/api/model/condition/MissingCondition.java
api/src/main/java/org/hawkular/alerts/api/model/condition/NelsonCondition.java
api/src/main/java/org/hawkular/alerts/api/model/condition/RateCondition.java
api/src/main/java/org/hawkular/alerts/api/model/condition/StringCondition.java
api/src/main/java/org/hawkular/alerts/api/model/condition/ThresholdCondition.java
api/src/main/java/org/hawkular/alerts/api/model/condition/ThresholdRangeCondition.java
api/src/main/java/org/hawkular/alerts/api/services/DefinitionsService.java
commons/src/main/resources/alerting-local.xml
engine/src/main/java/org/hawkular/alerts/engine/impl/cass/CassDefinitionsServiceImpl.java
engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImpl.java
engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnPk.java
engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/model/IspnCondition.java
engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImplTest.java

- remove deprecated getCondition()
- add test
- add indexing
WIP - This is not yet working, there seems to be issues with inheritance
Getting this to work is not going well. May need to get some ISPN or HS help internally... I hit different problems using ispn dsl or hs dsl.

Condition support

---

api/src/main/java/org/hawkular/alerts/api/services/DefinitionsService.java
commons/src/main/resources/alerting-local.xml
engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImpl.java
engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImplTest.java

@lucasponce I added batch support for the backend cache config, for the remove.  If you think it's a bad idea we can talk about it.  I noticed I hadn't finished the TODO in removeTrigger after adding condition and dampening, so just wanted to finish that up.

Finish TODO section of RemoveTrigger

---

engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImpl.java
engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/model/IspnTrigger.java
engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImplTest.java

@lucasponce migrated over the group trigger support.  added a new indexed trigger field to easily query member triggers of a group. Also ported over the trigger enablement services.

ISPN Group Trigger Support

---

engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImpl.java

- Import/Export
- FullTrigger
- Notification Listeners
- group private methods at bottom
- fwiw, I prefer the private methods close to the relevant
public method but since lponce started this grouping at the
bottom I wanted to at least make it consistent.

ISPN Finish DefinitionsService Impl

---

api/src/main/java/org/hawkular/alerts/api/model/action/Action.java
api/src/main/java/org/hawkular/alerts/api/model/trigger/TriggerAction.java
api/src/main/java/org/hawkular/alerts/api/services/ActionsCriteria.java
api/src/main/java/org/hawkular/alerts/api/services/ActionsService.java
commons/src/main/resources/alerting-local.xml
engine/src/main/java/org/hawkular/alerts/engine/StandaloneAlerts.java
engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnActionsServiceImpl.java
engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImpl.java
engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnPk.java
engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/model/IspnAction.java
engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnActionsServiceImplTest.java
engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImplTest.java
engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnBaseServiceImplTest.java
engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImplTest.java

@lucasponce Please take a look.  I removed the unused executor from ispnalertsserviceimpl, we can put it back if you think we need it.  I also removed use of an executor in ispnactionsserviceimpl.  My understanding is the executor was needed only for c* concurrent writes.
Also, I wasted a lot of time trying to use the "in" operator in an ispn query.  I don't see that I was doing anything wrong but it seems not to work.  Instead I'm using an exploded "or" approach.

ISPN ActionsService support

---

api/src/main/java/org/hawkular/alerts/api/model/event/Alert.java
engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImpl.java
engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImplTest.java

Migrate pending methods for Alerts domain.
Events methods on following PR.

Complete Alerts business methods

---

hawkular-alerters/hawkular-elasticsearch-alerter/deployments/hawkular-elasticsearch-alerter-standalone/src/main/webapp/WEB-INF/web.xml
hawkular-alerters/hawkular-prometheus-alerter/deployments/hawkular-prometheus-alerter-standalone/src/main/webapp/WEB-INF/web.xml
hawkular-alerters/hawkular-prometheus-alerter/hawkular-prometheus-alerter-lib/pom.xml
hawkular-alerters/hawkular-prometheus-alerter/hawkular-prometheus-alerter-lib/src/main/java/org/hawkular/alerter/prometheus/rest/AlerterPrometheusApp.java
hawkular-alerters/hawkular-prometheus-alerter/hawkular-prometheus-alerter-lib/src/main/java/org/hawkular/alerter/prometheus/rest/Handler.java
hawkular-alerters/hawkular-prometheus-alerter/hawkular-prometheus-alerter-lib/src/main/java/org/hawkular/alerter/prometheus/rest/Notification.java
pom.xml

This adds a REST endpoint to the Prometheus alerter making it a notification receiver.  It converts and persists alert notifications as events.

Prom webhook

---

.gitignore
rest-handlers/src/main/java/org/hawkular/alerts/handlers/UIHandler.java
rest-handlers/src/main/resources/webroot/index.html

Added a /ui endpoint for static content where we can place all UI AngularJS resources.

Static content handler for UI

---

engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImpl.java
examples/hello-world/README.adoc
examples/hello-world/pom.xml
examples/hello-world/src/test/groovy/create_definitions.groovy
examples/hello-world/src/test/groovy/send_data.groovy
examples/hello-world/src/test/resources/hello-world-definitions.json

Found a bug when migrating examples.
Better to consolidate this one.
Next examples in following PRs.

Fix missing tenantId on actions

---

ui/src/main/ui/src/dashboard/dashboard-controller.js
ui/src/main/ui/src/dashboard/dashboard.html
ui/src/main/ui/src/triggers/triggers.html

Add UI for the Aggregated Events example.

Complete Dashboard with support for Events coming from External Conditions

---

examples/group-triggers/README.adoc
examples/group-triggers/pom.xml
examples/group-triggers/src/test/groovy/clean_all.groovy
examples/group-triggers/src/test/groovy/create_group_trigger.groovy
examples/group-triggers/src/test/groovy/create_members.groovy
examples/group-triggers/src/test/groovy/update_group_trigger.groovy
examples/group-triggers/src/test/resources/group-trigger-definitions.json
examples/group-triggers/src/test/resources/update-group-conditions.json
ui/src/main/ui/src/app/controllers/app-controller.js
ui/src/main/ui/src/styles/app.css
ui/src/main/ui/src/styles/scss/main.scss
ui/src/main/ui/src/triggers/triggers-controller.js
ui/src/main/ui/src/triggers/triggers.html
ui/src/main/ui/template.html

Add basic pagination on Triggers UI
Added pagination to show large number of triggers on the UI.
Pretty basic yet, but the goal is to browse the GroupTriggers example without need of external REST query.

Port GroupTrigger examples

---

actions/actions-plugins/actions-kafka/src/main/java/org/hawkular/alerts/actions/kafka/KafkaPlugin.java
alerters/alerters-plugins/alerters-elasticsearch/src/main/java/org/hawkular/alerter/elasticsearch/ElasticsearchAlerter.java
alerters/alerters-plugins/alerters-elasticsearch/src/main/java/org/hawkular/alerter/elasticsearch/ElasticsearchQuery.java
alerters/alerters-plugins/alerters-kafka/pom.xml
alerters/alerters-plugins/alerters-kafka/src/main/java/org/hawkular/alerter/kafka/KafkaAlerter.java
alerters/alerters-plugins/alerters-kafka/src/main/java/org/hawkular/alerter/kafka/KafkaQuery.java
alerters/alerters-plugins/alerters-kafka/src/test/java/org/hawkular/alerter/kafka/KafkaAlerterTest.java
alerters/alerters-plugins/alerters-kafka/src/test/resources/log4j2.xml
alerters/alerters-plugins/alerters-prometheus/src/main/java/org/hawkular/alerter/prometheus/PrometheusAlerter.java
alerters/alerters-plugins/pom.xml
api/src/main/java/org/hawkular/alerts/api/model/event/EventField.java
api/src/main/java/org/hawkular/alerts/api/model/trigger/TriggerKey.java
dist/pom.xml
engine-extensions/events-aggregation/src/main/java/org/hawkular/alerts/extensions/EventsAggregationExtension.java
engine/src/main/java/org/hawkular/alerts/engine/cache/PublishCacheManager.java
examples/kafka-action/src/test/resources/kafka-action-definitions.json
examples/kafka-topics/README.adoc
examples/kafka-topics/create-definitions.sh
examples/kafka-topics/kafka-triggers.json
itests/pom.xml

This PR adds a new Alerter to listen Apache Kafka topics and parse records as Data or Events.
Also an example is added to demo this new functionality.

Kafka Alerter and examples

---

ui/src/main/ui/src/alerts/alerts-controller.js
ui/src/main/ui/src/alerts/alerts-module.js
ui/src/main/ui/src/app/app-module.js
ui/src/main/ui/src/app/controllers/app-controller.js
ui/src/main/ui/src/dashboard/dashboard-controller.js
ui/src/main/ui/src/dashboard/dashboard.html
ui/src/main/ui/src/events/events-controller.js
ui/src/main/ui/src/events/events-module.js
ui/src/main/ui/src/events/events-service.js
ui/src/main/ui/src/events/events.html

Ok, a first Events tab to complete the details of what we show.
Mostly reused the Alerts tab and linked from Dashboard.
Ah, also put in order Dashboard, Alerts, Events as it is close and leave to the end the definitions/actions.
I'm going to optimize some missing formats on Events but in a following PR.

Add Events tab into UI

---

hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/EventsITest.groovy

This PR adds more testing on Events.
Also it will use travis to validate if tests are passing on the CI.

HWKALERTS-275 Additional tests on Event queries

---

ui/src/main/ui/src/actions/actions-controller.js
ui/src/main/ui/src/actions/actions.html
ui/src/main/ui/src/alerts/alerts-controller.js
ui/src/main/ui/src/alerts/alerts.html
ui/src/main/ui/src/app/app-module.js
ui/src/main/ui/src/app/controllers/app-controller.js
ui/src/main/ui/src/dashboard/dashboard-controller.js
ui/src/main/ui/src/dashboard/dashboard.html
ui/src/main/ui/src/events/events-controller.js
ui/src/main/ui/src/events/events-module.js
ui/src/main/ui/src/events/events.html
ui/src/main/ui/src/triggers/triggers-controller.js
ui/src/main/ui/src/triggers/triggers.html

Capture missing errors from backend and show them into a toast pattern.

Toast notifications

---

.travis.swagger.sh
.travis.yml
hawkular-alerts-rest/hawkular-alerts-rest-api/pom.xml

v1 API Doc should be generated and managed from this branch.

v1 API doc managed from 1.8.x branch

---

pom.xml

- continue to skip all the checkers by default
- enable checking with -Pcheck
@lucasponce sorry for the confusion, should have created this PR yesterday.  I think this simplifies things, just add -Pcheck if you want to run the checkers.

Fix root pom profile issue

---

api/src/main/java/org/hawkular/alerts/api/services/StatusService.java
dist/src/main/resources/config/log4j2.xml
engine/pom.xml
engine/src/main/java/org/hawkular/alerts/engine/StandaloneAlerts.java
engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java
engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImpl.java
engine/src/main/java/org/hawkular/alerts/engine/util/Utils.java
engine/src/test/resources/hawkular-alerts.properties
engine/src/test/resources/log4j2.xml
itests/src/test/java/org/hawkular/alerts/engine/PersistenceTest.java
itests/src/test/resources/log4j2.xml
pom.xml

- remove some leftover cassandra references
- fix small issue in severities query
@lucasponce A few small cleanups I came across when working on 1.8.

Minor Tweaks

---

commons/src/main/resources/ispn-alerting-distributed.xml
commons/src/main/resources/ispn-alerting-local.xml
commons/src/main/resources/ispn-alerting-local.xml.debug
commons/src/main/resources/ispn-alerting-local.xml.ispn

@lucasponce Some minor cleanup

Remove unused schema cache

---

hawkular-alerts-rest-tests/src/test/groovy/org/hawkular/alerts/rest/AbstractITestBase.groovy
hawkular-alerts-rest/hawkular-alerts-rest-api/src/main/java/org/hawkular/alerts/rest/StatusHandler.java

Minor change to aling the same status value from inventory and alerting.

Align status endpoint with UP/DOWN

---

alerters/alerters-plugins/alerters-elasticsearch/src/main/java/org/hawkular/alerter/elasticsearch/ElasticsearchQuery.java

fix mapping of elasticsearch number values to hawkular event data.

HWKALERTS-286

---

rest-handlers/src/main/java/org/hawkular/alerts/handlers/TriggersHandler.java

There were few copy-paste mistakes as well as inconsistent description for triggerId

Fix groupId related documentation in REST API
